name: BUILD
on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: package database
              id: "database_package"
              uses: OctopusDeploy/create-zip-package-action@v3
              with:
                package_id: ProductDB
                version: "v001"
                base_path: "**/*"
                files: "**/*"
                output_folder: packaged
            - name: Upload artifacts to Github
              uses: actions/upload-artifact@v3
              with:
                name: assets-for-download
                path: packaged