name: BUILD
on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set Release Number
              id: ReleaseNumber
              run: |
                $versionNumber: "1.0.$GITHUB_RUN_NUMBER"
                Write-Output "APP_VERSION=$versionNumber" >> $Env:GITHUB_OUTPUT
            - name: Build and Test
              run: |
                # Your build commands here
                echo "Building version => 1.0.$GITHUB_RUN_NUMBER"
                # Run your build commands and tests
            - name: package database
              id: "database_package"
              uses: OctopusDeploy/create-zip-package-action@v3
              with:
                package_id: ProductDB
                version: 1.0.${{ steps.ReleaseNumber.outputs.APP_VERSION }}
                base_path: "db"
                files: "**/*"
                output_folder: packaged
            - name: Upload artifacts to Github
              uses: actions/upload-artifact@v3
              with:
                name: assets-for-download
                path: packaged